[font]
size = 9.0

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[keyboard]
bindings = [
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus",  mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0",   mods = "Control", action = "ResetFontSize" },
]
